saleweaver/python-amazon-sp-api

- sp_api/auth/access_token_client.py
- sp_api/auth/exceptions.py
- tests/api/fulfillment_inbound/test_fulfillment_inbound.py
In case amazon auth API is not successful then we need throw exception at right place.  Else it takes the error response as access token and later the SP API fails with UnAuthorisedError causing confusion about why token is not working when the error was in generating token itself.
> Add error handling for auth errors

- sp_api/base/aws_sig_v4.py
Any endpoint that has a query parameter requiring data in lists seems to create malformed querystrings while signing the request.
For example, a request to fetch orders with the following parameters:
```json
{
"CreatedAfter": "2021-04-16T05:49:18.307175",
"MaxResultsPerPage": 30,
"MarketplaceIds": [
"ATVPDKIKX0DER"
],
"OrderStatuses": [
"Unshipped",
"PartiallyShipped",
"Shipped",
"Canceled"
]
}
```
would expect the canonical querystring to unwrap each element in the `OrderStatuses` parameter while sorting them:
```
CreatedAfter=2021-04-16T05%3A49%3A18.307175&MarketplaceIds=ATVPDKIKX0DER&MaxResultsPerPage=30&OrderStatuses=Canceled&OrderStatuses=PartiallyShipped&OrderStatuses=Shipped&OrderStatuses=Unshipped
```
but since a dictionary was being used to manage the parameters, the querystring …
> fix: bad signature response with wrong canonical query string

- sp_api/api/reports/reports.py
Hi! 
I added [getReportSchedules](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md#get-reports2020-09-04schedules) to package. 
I was not able to find any instruction regarding contribution guidelines, so let me know if I need fix something! 
Best regards!
> Add `getReportSchedules` endpoint to Reports

- sp_api/base/helpers.py
When catching exceptions, you must rewind the IO/file device or the next encryption will encrypt nothing.
This error was detected in the Feeds API.
> Improve encryption handling after submitting empty feeds.

- sp_api/api/solicitations/solicitations.py
for solicitations API, the marketplace has to be passed as a URL parameter
* https://github.com/amzn/selling-partner-api-docs/blob/main/references/solicitations-api/solicitations.md#createproductreviewandsellerfeedbacksolicitation
```
Solicitations(credentials=credentials, marketplace=Marketplaces.US).create_product_review_and_seller_feedback_solicitation('113-xxx-xxx',marketplaceIds='ATVPDKIKX0DER')
```
> fix `'Missing or invalid request parameters: [marketplaceIds]'`

- sp_api/api/products/products.py
This PR adds the getItemOffers endpoint as given in the [selling-partner-api-docs](https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#getitemoffers) which "Returns the lowest priced offers for a single item based on ASIN".
> Add endpoint getItemOffers in Products

- sp_api/api/listings_items/listings_items.py
- sp_api/base/client.py
Same problem, endpoint need to 2 path params not only one:
<!DOCTYPE html>
Path | sellerId  required | A selling partner identifier, such as a merchant account or vendor code. | string
-- | -- | -- | --
Path | sku  required | A selling partner provided identifier for an Amazon listing. | string
The body param required need to be isolated from the **kwargs as data=kwargs.get('body')
<!DOCTYPE html>
Body | body  required | The request body schema for the putListingsItem operation.
-- | -- | --
The regular call could be:
seller_id = 'AXXXXXXXXXXXXX'
seller_sku = 'NEW-SKU-TR-7838383884'
issue_locale = 'es_ES'
marketplace_id = 'A1RKKUPIHCS9HS'
dictionary = {
"productType": "LUGGAGE",
"requirements": "LISTING",
"attributes": {
"recommended_browse_nodes": [
{
"value": "2008004031", …
> Fixed put_listings_item

- sp_api/api/catalog/catalog.py
Missing end point:
[https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md)
<h3>GET /catalog/v0/categories</h3><p></a>Description</h4><p>Returns the parent categories to which an item belongs, based on the specified ASIN or SellerSKU.</p><p>Usage Plans:</strong></p>
Plan type | Rate (requests per second) | Burst
-- | -- | --
Default | 1 | 40
Selling partner specific | Variable | Variable
<h4>Parameters</h4>
Type | Name | Description | Schema
-- | -- | -- | --
Query | MarketplaceId  required | A marketplace identifier. Specifies the marketplace for the item. | string
Query | ASIN  optional | The Amazon Standard Identification Number …
> Added endpoint /catalog/v0/categories

- sp_api/api/authorization/authorization.py
- sp_api/api/notifications/notifications.py
- sp_api/auth/access_token_client.py
- sp_api/base/client.py
Please review proposed solution for #193 and suggest changes, where necessary.
Notable changes:
* AccessTokenClient.grantless_data is no longer a property, it's a method accepting scope_value parameter.
* AccessTokenClient.get_grantless_auth() accepts scope parameter, with default value used by Notifications API - this is an attempt to remain compatible with code that was using `get_grantless_auth()` directly.
*  AccessTokenClient.get_grantless_auth() doesn't recreate TTLCache object, but rather clears existing one - I'm unsure if this is even necessary each time KeyError happens. IMO we could just add new value to cache, without purging all other keys. But even if we want to purge, creating new object creates a risk that 3rd party module keeping reference to `grantless_cache` will still …
> #193: Make get_authorization_code grantless, with migration scope.

- setup.py
This pull request allows usage of python-amazon-sp-api with the most recent version of the six library at the moment and possibly in the future (until 2.0).
> six dependency updated to version >=1.15,<2

- sp_api/api/product_fees/product_fees.py
Added to the GetMyFeesEstimateRequest
OptionalFulfillmentProgram  optional | An optional enrollment program to return the estimated fees when the offer is fulfilled by Amazon (IsAmazonFulfilled is set to true). | OptionalFulfillmentProgram
-- | -- | --
OptionalFulfillmentProgram
An optional enrollment program to return the estimated fees when the offer is fulfilled by Amazon (IsAmazonFulfilled is set to true).
Type : enum
Value | Description
-- | --
FBA_CORE | Returns the standard Amazon fulfillment fees for the offer. This is the default.
FBA_SNL | Returns the FBA Small and Light (SNL) fees for the offer. The SNL program offers reduced fulfillment costs on qualified items. To check item eligibility for the SNL program, use the getSmallAndLightEligibilityBySellerSKU operation of the FBA …
> Added OptionalFulfillmentProgram optional param to Product Fees

- sp_api/base/aws_sig_v4.py
Amazon has been giving me a signature error when I try to get prep instructions for a SellerSku which contains a space character. The error string saying what "should have" been signed has the space encoded as a %20, but the actual canonical_request has the space encoded as a plus.I think this is an Amazon bug and I shoudl be able to encode a space either way, so long as I am signing the actual string sent. Anyway replacing the + with %20 in the encoded query params allows the call to succeed.
> Change + to %20 in query params

- sp_api/base/client.py
Fixes #438 
This adds the possibility to use proxies when the request to SP-API is made.
The `proxies` parameter in `Client` is expected to be the same as in the `Request` library.
Example taken from the `Request` doc: https://docs.python-requests.org/en/master/user/advanced/#proxies
```
proxies = {
'http': 'http://10.10.1.10:3128',
'https': 'http://10.10.1.10:1080',
}
Finances(proxies=proxies).get_financial_events_for_order(order_id="123456789")
```
> Add proxies to request with Request

- sp_api/api/product_fees/product_fees.py
ProductFees() api does not encript SKU containing forward slash as described here #431 
As SKU is part of URL some of the chars in SKU could yield issue with URL formatting so we get `SellingApiForbiddenException` due invalid URL
Fix should handle this behavior.  
Also there is option to disable this conversion if needed as I imagine there will be cases where this will be problematic.
Currently it will default to `True` so all SKU will be quoted.
> Force user SKU quote

- sp_api/api/aplus_content/aplus_content.py
- sp_api/api/upload/upload.py
- sp_api/base/helpers.py
While trying the Upload api found that the endpoints of the apluscontent had problems because:
**1)aplus_content.py**
- The key marketplaceId:string | * REQUIRED is a required param so no need the add_marketplace which by default in the client is True
- The endpoints that need  post data as json body should be isolated so just pop it first and pass the left as params:
return self._request(kwargs.pop('path'), data=kwargs.pop("body"), params=kwargs, add_marketplace=False)
- The post_content_document_approval_submission need to be passed as params not data (think it will need to correct in the post_content_document_suspend_submission but I did not tried yet)
**2)upload.py**
Related with that when you tried to upload some image for the Aplus content in some special cases the md5 calculated …
> Correct AplusContent

- sp_api/api/feeds/feeds.py
In the default branch when I call get_feeds giving a nextToekn parameter I get an error message
sp_api.base.exceptions.SellingApiBadRequestException: [{'code': 'InvalidInput', 'message': 'NextToken cannot be specified with other input parameters', 'details': 'marketplaceIds;'}]
the patch prevnts that error.
> Do note send marketplaces in get_feeds if sending nextToken

- sp_api/api/inventories/inventories.py
Not sure if there's more context to this, but python-amazon-sp-api is using quote_plus() on the sellerSkus param, but afaict requests is already url-escaping it, so that's causing SKUs with spaces not to work and Amazon just returns nothing for them.  I think quote_plus() is unnecessary here?  The git blame says it was added as a fix but doesn't give any other context.
E.g. inventories.get_inventory_summary_marketplace(sellerSkus = ['my fun sku']):
Old behavior, doesn't work:
GET /fba/inventory/v1/summaries?sellerSkus=my%2Bfun%2Bsku
New behavior, works:
GET /fba/inventory/v1/summaries?sellerSkus=my+fun+sku
> Don't double-escape skus in get_inventory_summary_marketplace

- sp_api/base/__init__.py
- sp_api/base/exceptions.py
SellingApiNotFoundException wasn't in the list so 404s weren't being raised properly.  Also adds a few missing error types while we're at it.
> Add SellingApiNotFoundException to get_exception_for_code

- sp_api/base/identifiersType.py
CatalogItems(self, **kwargs) -> ApiResponse
See IdentifiersType  at
:link: https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#identifierstype
IdentifiersType required with identifiers(Max count : 20)
“Type of product identifiers to search the Amazon catalog for. Note: Required when identifiers are provided.”
```
Examples:
literal blocks::
from sp_api.base.identifiersType import IdentifiersType
res = CatalogItems().search_catalog_items(
marketplace=Marketplaces.US,
identifiers='B00XXX111,B00XXX112’,
identifiersType=IdentifiersType.ASIN)
```
```
"/catalog/2022-04-01/items": {
"get": {
"tags": [
"catalog"
],
"operationId": "searchCatalogItems"
"parameters": [
{
"name": "identifiers",
"description": "A comma-delimited list of product identifiers to search …
```
> IdentifiersTypes for v2022-04-01

- sp_api/api/product_fees/product_fees.py
- sp_api/base/client.py
- tests/api/product_fees/product_fees.py
This call, `POST /products/fees/v0/feesEstimate`, is unique among all other implemented calls in that its request and response bodies are arrays (of objects) at the top level; everything else has an object. This wouldn't work as parts of `Client` assume that the request is a dictionary, hence the addition of `wrap_lists`. This isn't perfect, as unfortunately `Client` actually treats `data` as both the request body _and_ metadata about the request, such as HTTP method. There may be a better solution that doesn't involve massive refactoring, but this is a fairly small change and does work for this use case.
A couple notes on the tests:
1. There are a few issues with the sandbox for the product fee calls. The first is that `OptionalFulfillmentProgram` cannot be `null`, failing validation; …
> Implement bulk call for ProductFees

- sp_api/api/products/products.py
- sp_api/api/products/products_definitions.py
- tests/api/products/test_products.py
The initial idea for addressing Batch operations, on [/batches/products/pricing/v0/itemOffers](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v0-reference#getitemoffersbatch) endpoint.
So the main idea is to:
1. Create request definitions, since batch requests (in our case [GetItemOffersBatchRequest](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v0-reference#getitemoffersbatchrequest)) are not explicitly stated in sp_api.api.products.products.Products.get_item_offers_batch function.
2. Allow as input request definition class or Python base types `requests_: Optional[Union[List[Dict], GetItemOffersBatchRequest]] = None`.
The main problem is that one has to state directly `"MarketplaceId"` in list of requests, but addressing that will require changing …
> Added GetItemOffersBatchRequest

- sp_api/base/client.py
- tests/client/test_base.py
It seems that it is worth adding timeout argument to network requests. By default, the current behavior is preserved, but you can override the timeout value for `Client`.
> Added timeout argument into requests

- sp_api/api/product_fees/product_fees.py
Fixes issue https://github.com/saleweaver/python-amazon-sp-api/issues/701
> change type annotation to be compatible with python<3.9

- sp_api/api/orders/orders.py
- tests/api/orders/test_orders.py
This PR adds the method to update_shipment_status for Amazon orders.
> add orders endpoint to update shipment status

- sp_api/api/feeds/feeds.py
- tests/api/feeds/test_feeds.py
Amazon returns various encodings on different venues:
US windows-1252
UK windows-1252
DE windows-1252
JP windows-31j
FR windows-1252
CA windows-1252
IT windows-1252
ES windows-1252
AU UTF-8
SG UTF-8
BR windows-1252
NL windows-1252
> get_feed_result_document uses encoding returned by Amazon.

- sp_api/base/helpers.py
- tests/client/test_helpers.py
Useful to have access to the underlying API method name (i.e for monitoring)
> sp_endpoint uses functools.wraps

- README.md
- sp_api/base/client.py
Avoid breaking the Client call if the response is not JSON serializable
> BaseClient - Catch JSONDecodeError properly

- docs/env_variables.rst
- sp_api/base/credential_provider.py
- tests/client/test_credential_provider.py
This change generalizes the implementation of `FromSecretsCredentialProvider`, to provide multiple implementations. Based on it, a new credential provider `FromCachedSecretsCredentialProvider` has been added.
The new credential provider uses the caching capabilities provided by [`aws-secretsmanager-caching-python`](https://github.com/aws/aws-secretsmanager-caching-python), to reduce the amount of calls to AWS Secrets Manager.
> feat: Add support for aws-secretsmanager-caching-python library

- sp_api/base/client.py
- sp_api/base/credential_provider.py
- tests/client/test_auth.py
Currently, the `CredentialProvider` constructor uses its own iterable of providers to retrieve and instantiate credentials. However, there are two challenges with the current approach:
* Reducing the list of default providers, to only include the ones that a specific deployment uses can only be done by mutating the `CredentialProvider.CREDENTIAL_PROVIDERS` list.
* Adding new, custom providers, or extending existing ones, is not possible.
This change allows users to implement and provide their own providers, or only provide the ones they are interested in, to be used.
> feat: Allow injection of custom Credential Providers

- requirements.txt
- setup.py
`six` is no longer being used within the codebase, and is not needed as the project does not support Python 2 anymore.
> misc: Remove six dependency

- setup.py
Adding a new `extras_require`, so projects can install `aws-secretsmanager-caching` as an indirect dependency.
> misc: Add setuptools extra for AWS caching

- sp_api/auth/access_token_client.py
Raises type error when `credentials` in `AccessTokenClient` is not an instance of `CredentialProvider`.
Closes #852
> 852 - Ensure credentials is instance of CredentialProvider

- sp_api/api/feeds/feeds.py
Hi,
first of all thanks for this awesome library, it helps us a lot with our daily tasks :+1: 
Regarding the [`/feeds/2021-06-30/documents`](https://github.com/amzn/selling-partner-api-models/blob/main/models/feeds-api-model/feeds_2021-06-30.json#L949) endpoint, this library provides a very comfortable way of creating a feeds document.
However, the implementation of this endpoint in this library does more than the actual endpoint:
While the endpoints only specifies a response containing a presigned url, which can then be used to upload a file, this library enforces to provide a file.
In case you have the file, this is very convenient, but this is not always the case and does not work with the sandbox api.
So I suggest to only do the upload if a file is actually provided. By not changing …
> misc: allow empty files for create_feed_document api

- sp_api/base/helpers.py
Hi,
Thank you so much for putting effort into this wrapper as it has created so much value for us. The thing is lately I ran into an issue in `ListingsItems` in fact I need to get a list of items with the given SKU (DE-36023/4) which has special characters including slash which causes an unexpected behavior:
```
Traceback (most recent call last):
File "/Users/daydad/Desktop/forks/python-amazon-sp-api/test.py", line 10, in <module>
d = get_listingitems_per_sku(customer, "DE-36023/4")
File "/Users/daydad/Desktop/forks/python-amazon-sp-api/test.py", line 5, in get_listingitems_per_sku
return ListingsItems(credentials=customer.get_credentials()).get_listings_item(sellerId=customer.selling_partner_id, sku=sku, includedData="summaries,issues,attributes,offers").payload
File …
```
> Encode slash character in get_listings_item

- setup.py
Upper version bounds are generally a nuisance, as they unnecessarily block upgrades. See this post for a summary and then a long discussion: https://iscinumpy.dev/post/bound-version-constraints/
I noticed you have upper version bounds, then you spend a lot of time updating them as in eb7be07, 8ae01c8 , 2c90d24, 73ceb7c. (And if you don't release these updates, you block users from upgrading themselves, which could block important security fixes!)
This PR removes the upper version bounds. You can remove all that busywork and help users out. In the rare case a new version of a dep causes problems, users should be pinning, and you can release a fix.
> Remove version upper bounds

- sp_api/base/marketplaces.py
According to the [official SP docs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids), `ZA` marketplace (South Africa) should be supported.
The launch was pushed back: https://businesstech.co.za/news/business/659231/amazon-pushes-back-launch-of-south-african-marketplace/, but it's good to have it on supported list already
> Added ZA marketplace

- sp_api/base/credential_provider.py
Hi again,
... and again thanks for this awesome library :-D
I want to discuss the `required_credentials` in the [credential_provider](https://github.com/saleweaver/python-amazon-sp-api/blob/master/sp_api/base/credential_provider.py#L19).
It forces providing an 'aws_access_key' and a 'aws_secret_key'.
However, the default behavior of boto is to use the environment. This is especially handy if you run it it a lambda or ecs task definition, where you already attached a role to lambda / task.
In these cases, the environment has (short-living) session credentials which are then picked up by the underlying boto library.
Therefore, you usually want to omit the credential fields in the library.
Sadly, most tutorials from AWS and the internet always provide credentials, which gives the impression …
> remove 'aws_access_key' and 'aws_secret_key' from required credentials

- sp_api/api/product_fees/product_fees.py
Previously when calling `get_product_fees_estimate` after a `SellingApiRequestThrottledException` with the `throttle_retry` decorator, an error would occur because the request object had data removed.
To fix I removed the removal of the values from the object and passed them down into the `_create_body` function instead
> Fix product fees estimate not being able to retry requests

- sp_api/api/products/products.py
- sp_api/api/products/products_definitions.py
- tests/api/products/test_products.py
This pull request implements the [Products_v0_getListingOffersBatch](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v0-reference#getlistingoffersbatch) endpoint, mirroring the code style of [Products_v0_getItemOffersBatch](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v0-reference#getitemoffersbatch).
- Added test using sandbox test values to verify new endpoint. 
- Corrected preexisting failing GetItemOffersBatch test using sandbox test values, allowing all existing "Products" client tests to pass.
> Added Products/v0/getListingOffersBatch endpoint. Fixes #1067

- sp_api/api/sales/sales.py
Fixes:
https://github.com/saleweaver/python-amazon-sp-api/issues/1119
> Fixed datetime format issue for getOrderMetrics API call

- README.md
- docs/index.rst
The current docs file `index.rst` redirects to `https://sp-api-docs.saleweaver.com/` on load. This PR removes the redirect and updates the readme links to the readthedocs.io domain. This should resolve issues #1185 and #1190
> Prevent hardcoded redirect to https://sp-api-docs.saleweaver.com/

- credentials.yml
- docs/config_file.rst
- docs/env_variables.rst
- docs/examples/authorisation_example.rst
- docs/from_code.rst
- sp_api/base/client.py
- sp_api/base/credential_provider.py
- tests/client/test_auth.py
- tests/client/test_base.py
- tests/client/test_credential_provider.py
As a follow-up for #1203, any reference to AWS access/secret key, and role ARN is being removed.
> fix: Remove AWS IAM auth leftovers

- sp_api/api/feeds/feeds.py
Hi,
I had trouble uploading `POST_FLAT_FILE_LISTINGS_DATA` Feeds with the `create_feed_document` method to the Amazon Germany marketplace that contained special German characters (ä,ö,ü,ß). The encoding of the characters that arrived at Amazon seemed wrong, even though the ISO-8859-1 encoding should be correct. I'm not 100% sure if my code change is correct in all cases, but it did the trick for me.  
Decoding in that place seems wrong to me, because it converts already encoded upload data back to `str`, which is then uploaded with the default encoding of requests which I think is UTF-8, which Amazon cannot handle.
Thanks for the great library!
> Fix create_feed_document upload encoding

- sp_api/auth/access_token_response.py
Get the value of the **expires_in** correctly, according to [documentation](https://developer-docs.amazon.com/sp-api/docs/website-authorization-workflow-renew#step-1-reauthorize-from-manage-your-apps-page)
and tests via postman
> [FIX] sp_api/auth: expires_in value in AccessTokenResponse

- sp_api/api/fulfillment_inbound/fulfillment_inbound.py
The get_shipment operation on the fulfillment_inbound API (only available on 2024-03-20 version) has the wrong endpoint in the current release. It is currently calling '/inbound/fba/<version>/inboundPlans/{inboundPlanId}' but according to the documentation the correct endpoint is '/inbound/fba/<version>/inboundPlans/{inboundPlanId}/shipments/{shipmentId}'.
Here is a pull request that corrects the endpoint. Please let me know if this makes sense and if I can be helpful in any way!
> fulfillment_inbound get_shipment endpoint fix

- sp_api/api/fulfillment_inbound/fulfillment_inbound.py
Try to allign with `Fulfillment Inbound API v2024-03-20 Use Case Guide` as per [documentation](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide "documentation")
Added new endpoints:
- [confirm_delivery_window_options](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#confirmdeliverywindowoptions "confirm_delivery_window_options")
- [generate_delivery_window_options](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#generatedeliverywindowoptions "generate_delivery_window_options")
- [list_delivery_window_options](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listdeliverywindowoptions "list_delivery_window_options") …
> Fulfillment Inbound API v2024-03-20 new delivery endpoints

- sp_api/api/sellers/sellers.py
Adding in the `sellers/v1/account` route added to the API on August 14, 2024
via: https://developer-docs.amazon.com/sp-api/docs/sp-api-release-notes#august-14-2024
> /sellers/v1/account route

- sp_api/base/client.py
Fixing this error
```
File “/usr/local/lib/python3.8/site-packages/sp_api/base/client.py”, line 124, in _check_response
js = res.json() or {}
File “/usr/local/lib/python3.8/site-packages/requests/models.py”, line 917, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0
```
> Fix wrong JSONDecodeError import dependency
