saleweaver/python-amazon-sp-api

sp_api/auth/access_token_client.py

* Uses reset token in cache key (access token). This allows to work with multiple oAuth connections.

Allow multiple auth

---

sp_api/api/products/products.py

Added competitivePrice endpoint
Altered price endpoint to include ItemCondition for ItemType Asin

Add competivePrice endpoint,  alter price endpoint

---

sp_api/api/finances/finances.py
sp_api/api/reports/reports.py

Added 3 Finances API Endpoint
Bug Fix in writing Report to a file

Added Finances API endpoints + Bug Fix in Reports API

---

sp_api/api/__init__.py
sp_api/api/fulfillment_inbound/fulfillment_inbound.py
sp_api/api/merchant_fulfillment/merchant_fulfillment.py
sp_api/base/__init__.py
sp_api/base/helpers.py
tests/api/fulfillment_inbound/test_fulfillment_inbound.py
tests/api/merchant_fullfillment/test_merchant_fullfillment.py
tests/api/orders/test_orders.py
tests/api/products/test_products.py

- Added merchant-fulfillment model and its tests.
- Added nest_dict function to facilitate the creation of nested dictionaries from flat dictionaries.
- Fixed several tests
The get_shipments test does not work, with the sandbox data, as I had mentioned.

merchant- fulfillment, nested dict function, test merchant, fix test

---

sp_api/base/report_headers.py

Started listing report headers for a limited amount of reportstypes.
Preferably this should be in it's own branch until a sufficient amount of report headers are listed ?
Up to you,

Started adding report_headers as Enums

---

sp_api/api/products/products.py

Hi!
This is my suggestion for an implementation of https://github.com/saleweaver/python-amazon-sp-api/discussions/117#discussion-3308272
Is it fine for you like this? Appreciate any comments!
Best regards
Philip

✨: new endpoint getListingOffers in Products

---

setup.py
sp_api/api/__init__.py
sp_api/api/shipping/shipping.py

WIP for now!
I can call `get_account()` without errors. I will follow up and squash it down with better comments like the original source.  (was the original source generated somehow from the swagger models/api?)

[ADD] api.shipping

---

sp_api/api/listings_items/listings_items.py

ListingsItems API delete_listings_item will not work as expected #169

Fixed delete_listings_item

---

sp_api/api/listings_items/listings_items.py

Same solution for sister def patch_listings_item
test payload:
'payload': {'issues': [],
'sku': 'NEW-SKU-TR-7838381234',
'status': 'ACCEPTED',
'submissionId': 'b255039e9c204d53b2fc52e9c4XXXXX'}}

Fixed patch_listings_item

---

sp_api/api/listings_items/listings_items.py

The request is clean now>
"PATCH /listings/2020-09-01/items/A01234567890123/YOUR-SKU-123?marketplaceIds=A1RKKUPIHCS9HS&issueLocale=es_ES HTTP/1.1" 200 128

Solve as kwargs pop to avoid send body as params

---

sp_api/api/reports/reports.py

In Japan, the character code of the report file was cp932, so the default decode character code iso-8859-1 of the function get_report_document can be changed with an argument.

added arg to get_report_document in reports

---

sp_api/base/client.py

Fix issue Error with multiple credentials #252

fix role cache

---

sp_api/api/messaging/messaging.py

since we have marketplace_id, we don't need to get it from user. I just added params and added marketplace_id into it.

messaging api invalidinput error for marketplaceIds fixed

---

docs/endpoints.rst
docs/endpoints/listings_restrictions.rst
make_endpoint/make_docs.py
make_endpoint/make_endpoint.py
setup.py
sp_api/api/__init__.py
sp_api/api/listings_restrictions/listings_restrictions.py

Created ListingsRestrictions endpoint and doc

added listings_restrictions endpoint and docs

---

sp_api/base/ApiResponse.py

Adding a new alternative to get next_token from response.

Hot fix ApiResponse

---

sp_api/api/fulfillment_inbound/fulfillment_inbound.py

The endpoint FulfillmentInbound().item_guidance was missing the data passed on the request.

fixing itemGuidance request: data was missing

---

sp_api/api/products/products.py

Hi @saleweaver ,
after using the other methods I found some issues on the optional/required params so I fixed all according the docs:
[https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v0-reference](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v0-reference)
```
from sp_api.api import Products
from sp_api.base import SellingApiException, Marketplaces
import logging
```
The examples to use here, tested and working:
get_product_pricing_for_skus
```
condition = "New" # "New", "Used", "Collectible", "Refurbished", "Club"
type = "B2B"  # "B2C, B2B"
sku_list = ['SKU01', 'SKU02']
try:
res = Products(account=store, marketplace=marketplace).get_product_pricing_for_skus(
seller_sku_list=sku_list,
item_condition=condition,
offer_type=type
)
result = res.payload …
```

review whole endpoint Product Pricing

---

sp_api/api/messaging/messaging.py

fix Messaging API

---

sp_api/api/upload/upload.py

[https://developer-docs.amazon.com/sp-api/docs/uploads-api-reference](https://developer-docs.amazon.com/sp-api/docs/uploads-api-reference)
POST /uploads/2020-11-01/uploadDestinations/{resource}
Kindest regards,
@denisneuf

correct endpoint url for Uploads API

---

sp_api/util/load_all_pages.py

load_all_pages was sleeping X times, where X is the page number it was on, instead of once per page.  This PR makes it non-recursive and hopefully fixes that and a couple other small bugs like doing two calls before the first sleep, and not passing the extras dict on the first call.

Fix buggy load_all_pages decorator

---

sp_api/api/products/products.py
sp_api/api/products/products_definitions.py
tests/api/products/test_products.py

This is based on the PR https://github.com/saleweaver/python-amazon-sp-api/pull/655 by the original author, @kp-sellectra.  It looks like that one has been abandoned, so I implemented a suggestion to fix a failing test and created this one. Hope I'm not stepping on anyone's toes.

Add get item offers batch

---

sp_api/base/marketplaces.py

This PR adds the new European marketplace "Belgium"

Add marketplace details for Belgium

---

sp_api/api/feeds/feeds.py
sp_api/api/reports/reports.py
sp_api/auth/access_token_client.py
sp_api/base/client.py

I've found some places where proxy does not use:
* boto client
* reports and feed api
* `AccessTokenClient._request`

Fixed proxy usage

---

setup.py

PR #934 was merged, but the merge commit was resolved by removing all its changes. This PR re-applies its changes to remove the upper version bounds.

Re-remove upper version bounds

---

sp_api/api/upload/upload.py

fix upload
